exercice(test_catalogue ${CMAKE_CURRENT_SOURCE_DIR}/test_catalogue.cpp)
target_link_libraries(test_catalogue PRIVATE bibliotheque nlohmann_json::nlohmann_json)
if(BUILD_INTEGRATION_TESTS)
  find_package(PostgreSQL REQUIRED)
  add_library(catalogue_bdd STATIC ../src/catalogue_bdd.cpp)
  target_link_libraries(catalogue_bdd PUBLIC bibliotheque PRIVATE PostgreSQL::PostgreSQL options_cours)
  exercice(test_integration ${CMAKE_CURRENT_SOURCE_DIR}/test_integration.cpp)
  target_link_libraries(test_integration PRIVATE catalogue_bdd PostgreSQL::PostgreSQL)
  set_tests_properties(test_integration PROPERTIES LABELS integration TIMEOUT 120)
endif()
